### PR TITLE
Add new explorer: thetangle.org

### PR DESCRIPTION
**Pull request by viossat**

### CODE REVIEW

**Comment by ertugrulyilmaz** [comment]
Hi @viossat ,

Thanks for sharing a site. 
This site does not work on Safari. Maybe someone who is owner of site will fix it

**Comment by viossat** [comment]
It works on my side with Safari 10.1.2 and Safari on iOS 10.3.3.

**Comment by viossat** [comment]
@ertugrulyilmaz , please reconsider this PR. An issue with localStorage has been fixed.

**Comment by ertugrulyilmaz** [comment]
hi @viossat 
i added link to tools section. 
thanks.

**Pull request closed without merging**
